import type { Metadata } from "next";

import "repo-ui/globals.css";
import { geistMono, geistSans } from "./fonts";
import RootProvider from "./root-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): React.ReactElement {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<RootProvider>{children}</RootProvider>
			</body>
		</html>
	);
}
