import { RootProvider } from "fumadocs-ui/provider";
import "./global.css";
export const metadata = {
	title: "Welcome to docs",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className="flex flex-col min-h-screen">
				<RootProvider>{children}</RootProvider>
			</body>
		</html>
	);
}
